### ISSUE TITLE
SquidLib Tool needs better/more instructions

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#111]
There's several options in the tool that seem self-explanatory, but could do with documentation here as part of a setup tutorial.

For example, which Extensions should be selected when setting up a bare bones SquidLib project?

I'm thinking a page just for setting up the tool based environment, along with the more advanced options listed in the main page. Then right at the beginning of the main page we could link to that setup page so people can see it without polluting the features section.

**Comment by tommyettinger** [comment]
The defaults are there for a reason! Only SquidLib starts out checked, and it is the display code (there should be a hover tooltip or something; there's a description of it as the display code in the SquidSetup source, but that description may show up in weird places or at the wrong times). None of the others start out checked. When SquidLib is checked, it handles any dependencies it has, so you shouldn't see a difference by checking LibGDX, since it's already included in SquidLib is checked. The only reason for including LibGDX as a separate option is if you want to handle rendering yourself and use graphics, not using SquidLib for display, but to still use the FOV/dungeon-gen/pathfinding/etc. code in the squidlib-util project (always required here). You could also have nothing checked, and use console output. Any of the other extensions are there because they're LibGDX extensions and people may want them in a convenient place if they're used to using them in LibGDX projects; most roguelikes have no use for them except maybe gdx-ai or ashley.

I agree that the setup tool could use an instruction page of some kind. I'm thinking the wiki may be the right place. I'm also working on some ready-to-use demos in a separate repo, https://github.com/tommyettinger/SquidLib-Demos , that depend on release versions of SquidLib and not the master version that the demos in test folders use. I don't think any of those demos are especially usable yet, and some need to be updated.

**Comment by tommyettinger** [comment]
OK, this is at least mostly fixed. There's a setup documentation page on the wiki, linked from the front page instead of filling the front page, and the setup tool mentions that the defaults don't need changing for text-based games.
