### ISSUE TITLE
SquidLayers.put does not properly set the background

### ISSUE THREAD

**Issue by omcnoe** [SquidPony/SquidLib#121]
When using the put method with the signature SquidLayers put(int x, int y, char[][] c, int[][] foregroundIndex, int[][] backgroundIndex, int[][] backgroundLightness), the background color is not set correctly.

I have 4 arrays that I pass into that function, but no matter what I set the values of backgroundIndex and backgroundLightness too, the only tile that changes is the first character, and it uses the values for the background of the last character.

Sorry if I've made an error, but I'm pretty sure that I haven't.

**Comment by tommyettinger** [comment]
There were a bunch of bugs in SquidLayers and I think this latest commit squashes them. There may be some similar areas that deal with 2D arrays of "something" that need fixing as well, but I think that I got at least most of the relevant code fixed. I also added a simple application/"demo"/thing so I can debug this kind of problem, where the possible causes for a bug are all in just a few places, in a test-like format more easily. Thanks for reporting this! Please let me know if there's any feature requests you have as Uniscape gets going!

**Comment by omcnoe** [comment]
Wow, thanks for the really fast response. I've changed the build.gradle to use the latest version of SquidLib (which I've built locally), and it fixed my problem. When you generate a new SquidLib project it creates a Gradle project, but I noticed that the library project itself doesn't actually use Gradle? I was able to work out how to build it though.

I'm not an amazing programmer, so I'm using this library as an exercise to get some experience. It looks like it's packed with features, 90% of which I'll never need! Hopefully I can make something that's at least interesting in some way.

**Comment by tommyettinger** [comment]
Glad you were able to build it on your machine with no problems; people have had some issues building in the past and that's why I moved SquidSetup to use JitPack. JitPack is a site/service that should be able to build a new version every time the latest version is requested a project made by SquidSetup. There's confusingly two versions of the Setup, one for stable releases and [one for the latest snapshot releases](https://github.com/tommyettinger/SquidSetup/releases/tag/v3.0.0-LATEST), and only the newer snapshot-based one uses JitPack; I should probably put the SquidSetup-LATEST build up in Releases, but it's currently linked from the README. The catch with the snapshots that Gradle might not request a new version, meaning JitPack won't build it, unless you tell Gradle to refresh, with `gradlew --refresh-dependencies` . If you changed the repositories other than adding `mavenLocal()` to them, it might need the JitPack repos added again if you want to try the refresh command. Also, the dependency is weirdly different when you use the JitPack version, and going from a JitPack install to a Maven local install changes

`compile "com.github.SquidPony.SquidLib:squidlib-util:-SNAPSHOT"`  (which may use `$squidlibVersion` as a shorthand for the `-SNAPSHOT` version)

to

`compile "com.squidpony:squidlib-util:3.0.0-SNAPSHOT"`

If you didn't need to change the dependency, then it probably kept depending on JitPack and got the latest build anyway :smiley: .

It is odd that we use Maven internally and Gradle for produced projects, but when SquidLib was just starting, Gradle was kind of awful. It continued being slow, though better in quality, when we switched to Maven about a year ago, and at that point we weren't sure Gradle would be a good thing to switch to. Since then Gradle has gotten much faster and Maven has hardly been updated, but since we don't need anything particularly difficult with the builds we'll probably keep them where they are to avoid breaking things. SquidSetup is based on LibGDX's setup tool, which produces Gradle projects since they handle platform-specific code better.

**Comment by omcnoe** [comment]
I had originally changed my build.gradle to depend on the local version using
`repositories {
    ...
    flatDir {dirs "path/to/squidlib-jar-directory"}
    ...
}`
and then `compile name: "squidlib"` under dependencies. But using JitPack is so much easier, thank you. I've changed it to build using the JitPack -SNAPSHOT version now.
