### ISSUE TITLE
The exact Gradle dependencies for a LibGDX project

### ISSUE THREAD

**Issue by czyzby** [SquidPony/SquidLib#126]
Could you post which library versions should be currently used in a LibGDX project to support all platforms? It seems that `squidlib` is in `3.0.0-b3` version, while `squidlib-gdx` latest published version is still `3.0.0-b1`. What would be the correct dependencies setup and how can you support the GWT platform? (I imagine you'd need to include sources of both mentioned libraries and add a GWT inherit.)

**Comment by tommyettinger** [comment]
This is a tricky one with published releases on Maven Central. The name `squidlib-gdx` is from an older version, when we still had Swing as a backend and needed to distinguish them; now the module `squidlib` refers to the GDX textual display classes (`squidlib` previously referred to the Swing display, which was dropped because it was hopelessly slow). Because Maven Central is so unpleasant to deal with, newer versions of the setup tool (this one, https://github.com/tommyettinger/SquidSetup/releases/tag/v3.0.0-LATEST ) use JitPack to build individual commits from source. Even though building individual commits seems less stable, there's been very little API breakage despite active development, and we're all being careful to deprecate first instead of just removing a class or method.
I'd encourage you to try the setup tool, which can create a demo that works on HTML and Desktop from the starting gate, unless you have a complex existing project structure. You should be able to copy over code from just about any existing project, it just could be a hassle if you have a fragile Gradle setup. The current dependency versions, copied out of a project generated by SquidSetup, are:

```
        squidlibVersion = 'd6dc3ff62c'
        gdxVersion = '1.9.2'
        regexodusVersion = 'v0.1.2'
```

This assumes you have JitPack as a repository; this is one configuration that can be used to add it:

```
repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
}
```

This makes the dependencies of the core project look like:

```
    dependencies {
        compile "com.github.SquidPony.SquidLib:squidlib:$squidlibVersion"
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.github.SquidPony.SquidLib:squidlib-util:$squidlibVersion"
        compile "com.github.tommyettinger:RegExodus:$regexodusVersion"
    }
```

Note the first part of the dependency is not `com.squidpony` like with the Maven Central releases; JitPack builds from GitHub and so uses their URL. I won't post the full info on how to configure HTML from scratch here because I'm certain to miss something. Use SquidSetup to make a skeleton if you need to, then check what parts need to be copied over for your project. I'm still recommending using SquidSetup to make a new Gradle project and then copying existing code into it, but the skeletal copy approach may also work for your case. You would need to copy the various GWT files like `GdxDefinition.gwt.xml`, have the libGDX-style file hierarchy including an HTML module (which SquidSetup handles), and be using a version much more recent than 3.0.0-b3. The commit string that SquidSetup defaults to now is `d6dc3ff62c`, which is the most recent commit as of this writing. You can manually update later, there's instructions on the [SquidSetup release page](https://github.com/tommyettinger/SquidSetup/releases/tag/v3.0.0-LATEST). I hope this helps, ask away if you have more questions.

**Comment by czyzby** [comment]
I'm actually working on an alternative `gdx-setup` tool and want to add this extension, so the users could automatically include them in your project. Using Maven Central dependencies is the only way to go for this project, I'm afraid - that's why I asked for the exact dependencies and GWT inherit.

Anyway, if there's a project template that you'd like to contribute (basically a skeleton project for people that would like to use SquidPony to develop their app), I'd love your input on this. https://github.com/czyzby/gdx-lml/issues/20 While most users that want to mainly use SquidPony will probably simply start with the SquidSetup in the first place, there's a whole bunch of people that don't even know about and including a simple template project in a "global" `gdx-setup` app might be beneficial to this project. I'll eventually propose to replace the original, Swing-based (oh, the irony) `gdx-setup` with the one I posted.

**Comment by tommyettinger** [comment]
I think I can get a release on Maven Central sometime fairly soon. I'd like to fix a known "partial bug" first, where TextPanel works fine on its own, and has reasons you would use it now (it displays variable-width text with wrapping in a legible way), but does not display a scrollbar for unknown reasons. The number of unimplemented feature requests has shrunk quite a bit recently, and that might warrant a full 3.0.0 stable release. Some features came out of the blue, like XoRoRNG only having the algorithm it's based on released very recently. Others were requested based on a need in a project. ModularMapGenerator implements a style of generation someone requested by email (and implementing it was much more difficult than I thought, though the results I think are worth it), BenMcLean requested several generally handy features for his roguelike (like a GWT-compatible UUID replacement) that have mostly been easier to implement than I expected, and @smelc continues to send excellent PRs. @smelc , if any pull requests are in progress I can slow down the schedule for release, maybe so we can attempt to make scrollbars work again? I think Rectangle.java had some partially-complete code that was being used for something you were working on?

SquidLib has changed somewhat significantly in scope since 3.0.0-b3, with a dependency removed on GSON and one added on RegExodus. smelc and I replaced the old JSON data files for tilesets in squidlib-util with Java source files, with each of us generating an independent version (I don't remember whose version we picked). That eliminated the need for GSON. FakeLanguageGen compatibility was the driving force for RegExodus, and now SquidLib depends on it to be "mostly compatible with and typically with more features" when compared to java.util.regex on all platforms. RegExodus should be generally useful as a regex replacement for games that target HTML in addition to other platforms, though it needs more and better documentation for places where it adds features to the JRE implementation. On top of that, there's the most important fix, which is proper HTML support (landing in the code only after b3 was released), as well as numerous smaller bugfixes. Features have been added to cave generation, dungeon generation with rooms and sections of rooms, maze generation, text-based display on and off a grid, on-screen controls for mobile, color handling, random number generation and biasing, line drawing, utility classes like SpatialMap, and the list goes on. I do need to get RegExodus on Maven Central, and I just remember it was a massive pain to register a new project.

If it's an option for you, could you add the JitPack repository to your setup tool's list of searched repos? Then I could make a GitHub release of 3.0.0-b4 or 3.0.0 (either makes a permanently-the-same jar available on JitPack) so you have a stable release to base a dependency on. This would simplify using RegExodus as a dependency, both for SquidLib and any other projects that use LibGDX to target HTML and, say, desktop or Android.

**Comment by tommyettinger** [comment]
Oh, and gdx-lml looks like a great improvement, especially being able to pick templates and different languages. Good work there.

**Comment by smelc** [comment]
Unfortunately, I don't have the fix to TextPanel ready and won't have time to look at it until the end of next week, so don't wait for me.

**Comment by czyzby** [comment]
> If it's an option for you, could you add the JitPack repository to your setup tool's list of searched repos? 

That shouldn't have any significant effect on libraries look-up time, should it? I think it wouldn't be much of a problem, but then again - most people are used to stable releases rather than snapshots and their constant refreshing need. If you're planning a release pretty soon, maybe we should just wait a bit and add SquidLib once it's released.

I wouldn't mind if you posted some simple project using SquidLib that you'd like to be the "official" template for a new LibGDX application - I can convert it to a `gdx-setup`-compatible template myself. 

> Oh, and gdx-lml looks like a great improvement (...)

`gdx-lml` is actually a separate extension that allows you to build Scene2D GUI with HTML-like syntax. I made the new `gdx-setup` as a separate project (in a separate branch) and I'm currently too lazy to move it into a new repository. But it will happen. Some day. ; )

So, once you release a stable version or set up the template project, I'd appreciate if you left a comment in this issue, so I'll be notified.

**Comment by tommyettinger** [comment]
Oh yeah, JitPack doesn't need to use snapshots; for each release on GitHub, it creates versions that can be used as stable dependencies, builds them the first time anyone depends on them, and caches them so future depend-ers just use the cached jars. Lookup times are only affected if no one has depended on a release yet, and I would typically have tested the release before anyone else depends on it, meaning all lookups get the cached jars, for similar times to downloading from Maven Central. The repository URL for JitPack needs to be added to a generated project's maven, gradle, sbt, lein, etc. build file, which would make a library that uses JitPack-only libs unable to be uploaded to Maven Central because of their rules regarding other repositories (the current LibGDX setup tool adds a third-party repo too, JCenter, to get the plugin for GWT superdev mode). JitPack also does builds for individual commits when depended upon, but I probably would identify a single stable commit and just post a GitHub release at that version, so the version is more legible (like `v3.0.0-b4` instead of `a5b6df239e` or some commit string like that). The SquidSetup-LATEST release I put out just before my first comment in this thread uses a single commit as its "stable" release, and users can change the commit string on their own if they find a newer feature is needed (just like a normal version upgrade, it won't refresh on its own like a snapshot). I haven't updated the setup instructions yet to remove the earlier references to `--refresh-dependencies` when we still used `-SNAPSHOT` as a version, which wasn't working well with IDEs anyway.

The only reason I'd prefer using JitPack is because I am not looking forward to getting RegExodus on Maven Central, which would be a new project to register and thus a bureaucratic hassle. SquidLib would otherwise not be a problem to update a version on Maven Central, but it can't depend on any libs outside their repository, and so RegExodus would need to get on there first.

I'll clean up a sample project soon; I have a few that have varying quality for line-by-line documentation. What kind of "level of completeness" would you want in a sample? Unity3D ships with a single level of an action game as a demo project, for instance. I have a simple "walking around a random dungeon" demo that's probably the easiest for people to learn the library with, and some more complex examples that add monsters or the option to rebuild the dungeon to test styles of dungeon generation. You also mentioned that the new setup tool can use other build tools than Gradle; should I provide some kind of info for things like maven, lein, and sbt? Should I provide ports of a demo to a few other languages?

**Comment by czyzby** [comment]
> which would be a new project to register and thus a bureaucratic hassle

Unless you want a different group ID for it, publishing new artifacts is trivial. Once you get the permission to use a group ID, you no longer need to create Jira issues for new projects.

> I have a simple "walking around a random dungeon" demo that's probably the easiest for people to learn the library with, and some more complex examples that add monsters or the option to rebuild the dungeon to test styles of dungeon generation.

As far as examples of third-party extensions go, I think the sensible approach would be to provide at least 2 examples: a simple one (*how do I even include this library in my project?!*) and something more complex, to show extension's "true" capabilities (*what can I do with this library?*).

> You also mentioned that the new setup tool can use other build tools than Gradle (...)

I don't think I mentioned that - we do support different JVM *languages*, but now Gradle seems like one of the core tools for LibGDX.

`lein` and `sbt` seems to be rather language-specific - I'm pretty sure there are separate LibGDX wrappers for both Closure (`play-clj`) and Scala. Maven is a huge step backward from Gradle (imho), and modern Android applications usually rely on Gradle to manage dependencies, so we probably won't support Maven projects. Unless there are many requests to do so.

> Should I provide ports of a demo to a few other languages?

These won't work on GWT. As long as GWT is the default WebGL backend, I don't think these examples should be included.

We want the example projects to be executable on each platform, unless the library itself doesn't support it at all. If SquidLib works on GWT, its examples should be written in "pure" Java 1.6, I think.

**Comment by czyzby** [comment]
As far as JitPack goes - if there's a possibility of using stable library versions, there's shouldn't be a problem in including it in our current Gradle setup. Just provide me the Gradle-based demo and I'll move all the necessary dependencies and repositories to `gdx-setup`.

**Comment by tommyettinger** [comment]
It turns out I already had registered the groupid I use for RegExodus, so I just did the normal steps and got it on Maven Central. I should be able to get a 3.0.0-b4 release of SquidLib on Maven Central sometime today or this weekend, but the demos may need some cleaning up. I'm planning on first improving an existing demo that shows the common task of generating a random dungeon, lighting the area nearby, and allowing input to move around, even on mobile platforms (where it pops up on-screen controls, though these could also be improved). That demo already uses Gradle, but I'd like to release SquidLib 3.0.0-b4 first so it has a stable dependency. After that, a "showing off" demo would be good, though the current demo that fills that role isn't great (it's being used as a testbed for new features, so the code has lots of redundant sections where different things are being tried out).

@czyzby , can you add the demos as they come in, or do you need them all with the release?

**Comment by czyzby** [comment]
Including project template is as simple as creating a new class file. We can include the SquidLib dependencies first and then just add project templates when you're ready. To be honest, most third-party extensions currently have no demos - it was just a suggestion that it would be nice (and beneficial) to include some kind of simple test project, so the newcomers could get started more quickly.

So sure, let me know when the dependencies are uploaded, and I'll add SquidLib to extensions.

**Comment by tommyettinger** [comment]
OK, 3.0.0-b4 is released, let's see if this is all the info...

`squidlibVersion` is currently `3.0.0-b4`. `regexodusVersion` is currently `0.1.3`. Both of these are on Maven Central now, so there's no need to change repositories after all that :smile: .

The module `squidlib-util` does not depend on anything but RegExodus, and games can use `squidlib-util` without depending on the text-based game display module in `squidlib`. Its dependencies for all platforms are:

```
"com.squidpony:squidlib-util:$squidlibVersion", "com.github.tommyettinger:regexodus:$regexodusVersion"
```

Its dependencies for HTML specifically are:

```
"com.squidpony:squidlib-util:$squidlibVersion:sources", "com.github.tommyettinger:regexodus:$regexodusVersion:sources"
```

Its GWT inherits are:

```
"squidlib-util", "regexodus"
```

The module `squidlib` is for text-based display on a grid, and as such is mostly useful to traditional roguelikes or prototypes of other turn-based games. It depends on LibGDX, and currently uses 1.9.2 but could probably update when a new version is released without much trouble. Its dependencies for all platforms are (not including libGDX, I assume you already have that as a dependency for the setup tool's projects):

```
"com.squidpony:squidlib:$squidlibVersion"
```

Its dependencies for HTML specifically are:

```
"com.squidpony:squidlib:$squidlibVersion:sources"
```

Its GWT inherits are:

```
"squidlib"
```

Any project that depends on `squidlib` for display should also depend on `squidlib-util`; `squidlib` uses several common classes and interfaces from `squidlib-util` and probably won't work without it. Gradle may download `squidlib-util` on its own since it's a dependency of `squidlib`. I'm not sure how I should specify this in the dependencies and inherits; the inherits for `squidlib-util` almost certainly would be in addition to `"squidlib"` already listed.

There's an odd sort of semi-dependency `squidlib` has on a bunch of assets; it can work just fine without any "library assets", but there is code in `squidlib` that knows how to configure some of the trickier distance field fonts and such. Several fonts were also modified heavily, both as .ttf and as bitmap font page, to work correctly on a grid. Any squidlib demo projects should include the contents of one of these archives in the android or core project's assets folder, and users can delete files they don't need as they see fit. I'll include these assets with the demo code as well.

[assets.zip](https://github.com/SquidPony/SquidLib/files/253761/assets.zip)

[assets.tar.gz](https://github.com/SquidPony/SquidLib/files/253760/assets.tar.gz)

I'm eager to see gdx-setup keep developing, @czyzby ! I'll work on the demo code soon, after I update the current SquidSetup -- hopefully for the last time, then I can switch over to recommending gdx-setup! If there's anything I missed, just give the word.

**Comment by tommyettinger** [comment]
CRAP. A one-character mistake in b4's dependency makes it fail as a library entirely. I'm pushing b5 ASAP with no new features other than "actually compiles".

**Comment by czyzby** [comment]
Keep in mind that TTF fonts are not supported by GWT, unless you use some custom cross-platform TTF loading code.

**Comment by tommyettinger** [comment]
Well aware of that TTF problem, but Freetype has trouble with the fixed-width rendering SquidLib uses anyway, so we always use bitmap fonts. When things need to scale or stretch we can use the distance field font technique, which alters a bitmap font with a shader to smooth out lines when it's upscaled. It looks like http://i.imgur.com/ZWfYafl.png in practice.
I'm editing the info comment I made yesterday to include the correct current version (changing b4 to b5)

**Comment by czyzby** [comment]
Are there any specific descriptions that you'd like to include for each library? I'll include all 3 in `gdx-setup`.

**Comment by tommyettinger** [comment]
Sure... How about:

`squidlib-util`: Procedural generation, AI, and other non-display code useful to grid-based games.

`squidlib`: Text-based display code meant for grid-based games, using LibGDX and squidlib-util.

`regexodus`: Regular expression engine that works equivalently on all targets, including HTML.

squidlib-parent is just an empty product of the packaging scheme Maven uses, it isn't a dependency.

**Comment by czyzby** [comment]
Done. Would you mind checking if the extensions are properly included? The libraries seem to be downloaded and linked as expected, but without an example project I'm unable to check it yet.

> squidlib-parent is just an empty product of the packaging scheme Maven uses, it isn't a dependency.

Move to [Gradle setup](https://github.com/czyzby/gdx-lml/blob/master/build.gradle#L87-L130)! It's worth it.

**Comment by czyzby** [comment]
About the assets: maybe the example project should use just one of the fonts, so `gdx-setup` size doesn't increase that much. We could leave a link (as comment in template code) where you can find other roguelike-optimized fonts and assets, but packing them all just seems not necessary.

I created an issue for the templates: https://github.com/czyzby/gdx-setup/issues/19
Don't hesitate to leave any suggestions. Once you're done with cleaning up your demos, let me know, so I can convert them to `gdx-setup` templates.

**Comment by czyzby** [comment]
OK, I think this issue can be closed, since now the library is pushed to Maven Central. When you finish the example applications, just leave a comment in the `gdx-setup` project.
