### ISSUE TITLE
PlannedAStar should probably be pulled out

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#130]
It looks like it is redundant with DijkstraMap present along with some issues referenced in the documentation for it

**Comment by tommyettinger** [comment]
Agreed, until AStar is improved (not sure what's making it so slow yet), DijkstraMap should be the focus. As an aside, it turns out DijkstraMap uses Breadth-First Search as its algorithm but produces the same data that Brogue calls Dijkstra Maps. The next set of work for pathfinding will go into finishing the alternate adjacency code used by CustomDijkstraMap, allowing portals, multi-level dungeons with monsters that use stairs, thin walls/corners, rotation with cost, and other fun stuff. I'll remove PlannedAStar in the next commit.

**Comment by smelc** [comment]
AStar is slow ? Damn I thought that DijkstraMap was the slow one, given that it offers much more features, I should reverse my implementation that uses AStar for long paths and DijsktraMap for short ones, is that correct ?
