### ISSUE TITLE
Setup tool gives questionable gradle info, and no gitignore

### ISSUE THREAD

**Issue by BenMcLean** [SquidPony/SquidLib#135]
Took me a while to figure out why I couldn't update SquidLib after making a new project See this commit here that seemed to fix it: https://github.com/BenMcLean/Planet-Generator/commit/ba7098161066bea664a9609c490bbbe7a05d3c6e

Ideally, the setup tool should take care of that, I believe.

Also, it would be nice to have it make you a proper gitignore.

**Comment by tommyettinger** [comment]
I have no idea how I'd get the setup tool to acquire the latest version string from JitPack, it may be possible though. I remember having severe issues using their "SNAPSHOT" version, where the IDE would get stuck on one old version but think it was still on the snapshot, so I'd lean away from using their automatic-latest-version attempt. It is a good idea to update some of this stuff though, like the setup tool; I haven't done an actual release in some time and a lot has changed or been added to since b6.

**Comment by tommyettinger** [comment]
I'll switch the default Maven coordinates to the ones JitPack uses (`com.github.SquidPony.SquidLib` instead of `com.squidpony.squidlib`) and default to a release on JitPack once the next stable or beta release is out. That should make updating easier; I can also try to improve the docs and add a .gitignore to projects made with SquidSetup. The plan is to ease away from SquidSetup since it's so cumbersome to update and is often long-behind libGDX's updates, and move to releases (on Maven Central, which is usually a requirement of many projects) that [czyzby's setup tool](https://github.com/czyzby/gdx-setup) can add as deps with a simple checkbox.
