### ISSUE TITLE
Nested ProbabilityTables would be nice

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#137]
Currently if I want to have it so that an item in the table is actually a new table to roll on again it's rather awkward. It would be nice if I could add tables as a weighted entry and when rolling get back an item as deep as needed if sub-table rolls are also needed

**Comment by SquidPony** [comment]
My use case for this is basically to be able to create something like "WoodTypeTable" that drops varying amounts of wood splinters and sticks and then reference it from anything made of wood as part of its destruction loot drop.

**Comment by tommyettinger** [comment]
Is there a limit on how many sub-table rolls can be performed, as the case usually is in tabletop games? D&D 3.x often has a d% roll of 100 produce 2 rolls on the same table, ignoring duplicate 100 results. It seems like this would best be handled with a function parameter (here, an inner class probably) that implements some interface, and a subclass of ProbabilityTable that requires its generic type to implement that interface. Then instead of returning the randomly obtained item, it calls a method (probably the only method) on it. That method could be recursive to "roll again", but that is only safe as long as the RNG is not very-badly-distributed (stack could overflow if the only thing it can roll is "roll again" recursively).

**Comment by SquidPony** [comment]
Good point about the recursion in the case where the same table is a child of itself. Defining it to not count itself in child results would be best, but I'd be okay with either defining a limit that you're not supposed to have references that can cause loops in the tree or with having it only return a single thing, which I would then have to check to see if it was of type ProbabilityTable and manually roll the next level on.

I'd also be okay with allowing technically infinite recursion with a warning, but that seems less good as a general practice unless you could set a max rolls depth on the table as well... klunky and still have to manually check if the final result was a table or an actual desired item.

**Comment by tommyettinger** [comment]
The last commit, cab6f61d9ab10ab08c7baac95259ea7f375b2d31 , should resolve this as long as nobody uses cyclical tables, and it warns quite a bit about that in the docs. One of the trickier things is having a set-like or map-key-like way to access the ProbabilityTable items and their weights, since those items are mutable, so we use hashing by identity for probability tables inside other tables. This is noted in the docs, but might not be especially clear because you can't make two identical ProbabilityTable objects and use one to get the other's weight (it needs to be the same reference to get an existing table). That said, that shouldn't happen much at all, and normal equality would break as soon as the RNG states changed even once, so doing it like this has other advantages. I hope you can make use of this at some point!
