### ISSUE TITLE
SVG support for dungeon generation

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#139]
It would be nice if something like https://xmlgraphics.apache.org/batik/ could be incorporated into dungeon generation so that layouts could be created in an external SVG editor and applied at run time as templates.

**Comment by tommyettinger** [comment]
Oh, barf. If "xmlgraphics.apache.org" doesn't make you immediately question why you are there in the first place, there may be a support group for that. SVG is such a bad fit for a grid-based layout... Raster would make sense, and in fact I've edited dungeons using XPM images (which are plain text files), but the amount of support it would take to handle, say, Bezier curves, as they approximate to char cells at every imaginable zoom level, is far beyond reasonable. I'm sure Batik supports a ton of stuff that we have no need whatsoever for, like rounding sharp corners, and lacks support for things that would be nice, like animations, while remaining not just a bulky dependency on its own but requiring sizable XML-based SVG files.

I do also think layouts should be editable outside of code, but XML meant to express resizable graphics is a poor way to do so.

**Comment by SquidPony** [comment]
Interesting. I'm open to other suggestions here for sure. I basically would like a way to design complex blueprints that can be resized to some extent. That being said I suppose the resizing isn't actually that important since scale for the grid would be just a straight multiplier on walls.

I'm going to close this one, it's probably a bad idea :)

**Comment by zacharycarter** [comment]
I've prototyped a few dungeon generation concepts in my POCs for my game derelict.

1) Dungeons that are laid out in the shape of a spaceship hull, with lock and key puzzles that are guaranteed to be solvable upon creation. This technique could be applied to other shapes too - it requires a black and white input bitmap which is basically a space map for how the dungeon layout is generated.

2) Dungeons which can be generated with generative grammars which allow you to design the overall mission-layout of the dungeon. You can create grammar rules to describe how the dungeon flows, and then the generator will use these rulesets to build a dungeon. The technique is described - http://pcgbook.com/wp-content/uploads/chapter03.pdf - I have a basic implementation of this working, however at the moment I can only produce grid-based zelda like dungeons.

I can expound upon both of these methods and perhaps help incorporating them into SquidLib if there is interest. LMK!

**Comment by SquidPony** [comment]
@zacharycarter there is interest on my part for sure

I worked a bit towards a generation grammar in the past but didn't have much success with it.

**Comment by tommyettinger** [comment]
Thanks to @zacharycarter 's recommendation of MetaZelda, I've brought in a fork of that project to the squidpony.squidgrid.mapping.locks package, and it seems to work so far. I need to test it more thoroughly, but it provides enough info to build at least the layout of rooms in a grid, and may have enough info to handle the keys (Symbols in MetaZelda terms) being placed in the correct rooms. The griddy nature of the map is pretty obvious, but the connectivity is actually pretty complex, especially with locks and keys. There's definitely too few doors being placed due to some other bug when you run LockTest, but that would be a bug in SectionDungeonGenerator.

Generation grammar would be great to have. Spaceship interior generation might be a little narrow in scope, since every game would want the ships to be in their own style, and would rewrite lib code anyway.

**Comment by zacharycarter** [comment]
I'll try to throw together some generative grammar stuff over the weekend. Nice work @tommyettinger .

**Comment by smelc** [comment]
Just in case someone wants to hack something, if there was a castle-generation algorithm; I'd be glad to use it, as I plan to do a special level on that theme (rogue defending the castle against invading monsters).
