### ISSUE TITLE
ArrayIndexOutofBoundsException in DijkstraMap

### ISSUE THREAD

**Issue by Zireael07** [SquidPony/SquidLib#144]
I got this crash on line 1283 several times when setting up my Dijkstra-using AI.

My best guess is that it happens if the AI is on the edge of the dungeon map and tries to check a direction which ultimately lies off-map. (The crash doesn't happen if none of my AI actors generate on map edges)

I could probably attempt a quick fix in my local files but I would prefer a proper fix in the repo :)

**Comment by tommyettinger** [comment]
Totally possible; I almost always do map bounding in the maps generated by the various dungeon generators. I'll get right on this. I don't think DijkstraMap has changed since 3.0.0-b8, but if you are using a version before that it will be different (it changed in b7 and thus in b8).

**Comment by tommyettinger** [comment]
Looks like you're using an older version or the line number isn't matching the same section. In 3.0.0-b8, which has had a large number of changes/fixes to DijkstraMap and related code, [here's line 1283](https://github.com/SquidPony/SquidLib/blob/v3.0.0-b8/squidlib-util/src/main/java/squidpony/squidai/DijkstraMap.java#L1283). I don't think any API broke in 3.0.0-b8's changed other than the cover-seeking pathfinding code (which never actually worked, and was removed) or any DijkstraMap code that used an FOVCache (since FOVCache is incompatible with GWT and has given much less than the performance boost that was hoped). It's possible the crash is surfacing after the point of an array access while setting blocked cells to the values of Coords passed as impassable (line 1280); if any Coord value has negative x or y, or is out of bounds in some way, then that could cause a crash but isn't currently checked (but could be). It's reasonable for me to add a check there, but I'm not sure that's the cause of this specific issue, since it isn't related to map edges.

**Comment by tommyettinger** [comment]
I'm guessing that the error was encountered in [veins-of-the-earth](https://github.com/Zireael07/veins-of-the-earth). If that's the case, try updating your build.gradle file to the current dependency versions. That would be `squidlibVersion = '0cd74bbd9b'` and `regexodusVersion = '0.1.9'`; there may have been some breaking changes since May 2016 (when your current version is from in that project), but performance and quality should be significantly better, in DijkstraMap especially. I need to update the getting started info badly, but people should probably not use SquidSetup any more. I can't keep it up to date very easily, and people may prefer https://github.com/czyzby/gdx-setup instead (which has SquidLib 3.0.0-b8 as a 3rd-party extension, plus a basic demo that shows how to do dungeon gen, pathfinding, text display, and input handling, among other things).

**Comment by Zireael07** [comment]
Thanks @tommyettinger I will update.

The SquidSetup part should be updated soon then, as other people might be falling in the same trap I did (following the readme, then discovering it's outdated)

**Comment by Zireael07** [comment]
Updating seems to have resolved the issue, thanks. 

@tommyettinger pinging to remind about updating the readme on SquidLib repo

**Comment by tommyettinger** [comment]
Readme is updated, not sure how suitable it is yet. Might be too long. Thanks for using SquidLib, looking forward to Veins of the Earth!
