### ISSUE TITLE
IMarkup and related classes have no documentation on them

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#153]
I'm not sure how to use them beyond just sending strings in.

**Comment by tommyettinger** [comment]
Good point. That is actually all they're there for; the main usage is via GDXMarkup, which just handles colored strings using libGDX's Label formatting technique, and doesn't do italics or underlining or anything like that. The idea is that library code can use `IMarkup<T>` formatting by calling `getMarkup(T)`, which produces a String that whatever does rendering can interpret as it will for that T. In GDXMarkup's case, it can getMarkup for a libGDX Color, and can be used to put the correct formatting into any `IColoredString<Color>` values the library prints. If I am guessing correctly, you have probably found GDXMarkup in LinesPanel, and the usage isn't clear, which is probably fine because there's no manual usage needed there beyond passing a GDXMarkup to the LinesPanel at some point. I'll add some docs across the related classes.

**Comment by tommyettinger** [comment]
A further example for IMarkup would be some implementation of `IMarkup<Creature>` that produces specific Strings that change in a time-based sequence when a Creature object is passed to its getMarkup() method, and time is taken from `System.currentTimeMillis()` or something like it. It wouldn't be unreasonable to have a GDX-specific `IMarkup<Creature>` that also colors the changing string using the same markup as GDXMarkup.
