### ISSUE TITLE
FOV returns doubles but ColorCenter wants floats for lerp

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#154]
I'd much prefer ColorCenter to also allow doubles for lerp (and maybe other operations, lerp is just the first one I hit)

**Comment by tommyettinger** [comment]
Sure, this is reasonable. Some places where floats show up need to use the float type because libGDX must use floats to send colors onto the GPU (Java lacks the structs that C/C++ OpenGL uses to transfer colors, and many older mobile GPUs don't support doubles on the GPU, so colors must be compacted into 31 of the 32 bits of a  IEEE single-precision float, with the bit set at position `0x01000000` always left as 0 to avoid producing `NaN` or infinite values). SquidPanel internally stores a 2D array of floats for colors to avoid allocating space for a full grid of Color objects, and to avoid GCing a large amount of objects when primitives could be used equivalently; this led to a significant speedup in the HashVisualizer code when it was implemented since that uses a 512x512 grid of 1 pixel by 1 pixel cells, each potentially with their own colors. For things like lerp and getHSV, though, the floats are mostly just due to how libGDX prefers floats for their better performance on mobile devices (and probably also desktops).

I'll leave this open until I've implemented at least some of these overloads.
