### ISSUE TITLE
SquidColorCenter returns com.badlogic.gdx.graphics.Color but should return squidpony.squidgrid.gui.gdx.SColor

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#155]
ColorCenter returns libgdx Color objects but I think it probably should return SColor objects instead since SColor can be a Color just fine

**Comment by tommyettinger** [comment]
The last statement is usually correct; an SColor can be used as a Color. "Usually," because some generic collections of generic collections may need a wildcard to specify `<? extends Color>` if they want to handle Color and all of its subclasses; where needed, SquidLib does this. However, for the rest of the issue, you have it backwards; `SColor`s have a name field that Colors do not have. We can take a Color and return a Color, or take an SColor (which extends Color) and return a Color (which may or may not have the SColor extension of a name), but if you take a Color, you cannot make it have a sensible name for an SColor. We currently can't manufacture a name from nothing to apply to a new SColor, and without a name, SColor is just a subtly less-friendly-with-generics alias for Color. There is a constructor in SColor that takes a Color as its only parameter, but since it doesn't supply a name (the color will be called "Unnamed", I believe), it's not especially useful.

You need to use Java at work more; it's clear you've been away from the pain of gimpy generics-and-inheritance code in Java for a little while. :smile: Even though C# has some confusing traits in its generics implementation, from what I've noticed observing derrickcreamer puzzling out difficult constraints on types, .NET's system in recent versions is a lot more powerful and a lot more expressive. I wonder what tools you've been working with lately in the buzzing shadows of Silicon Valley...

I'll close this because there's no reason why we should have named colors produced by SquidColorCenter if, as is the case for gradients, lighter/darker/saturation-altered/hue-altered colors, and filtered colors that may not resemble the original, the name won't be meaningful and just takes up at least one reference worth of memory per SColor. Those are, of course, the main usages of SquidColorCenter.

**Comment by SquidPony** [comment]
All the things you said are logical and correct, I concur.

Thanks to Unity, .net 2-ish and thanks to domain specific work, basically no generic work on the Java side in at least a year. You're right that I need to get more practice, and this issue is just one of likely many examples of my re-growing pains to come :)
