### ISSUE TITLE
DijkstraMap documentation does not explain what the optional rng passed in does

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#156]
Some of the methods that take an rng partially explain what's going on, but it would be nice if the class doc itself explained how the rng was used to choose between same-length paths.

**Comment by tommyettinger** [comment]
I could explain it a bit better if I knew what wasn't clear. I think it could be mentioned that the RNG is not used during `scan()` or the related `partialScan()` methods, but is used during most of the path-finding methods (`findPathPreScanned()` is an exception since it is meant to be more deterministic, and does not use the changing RNG member). It's pretty much exactly how you said it though; it randomly determines which of two or more cells to enter then the best-distance cells have an equal distance to a goal. It doesn't insert some kind of bias to favor some type of cell or movement over another, although technically this could be possible. Euclidean distance measurement raises the "costs" (more accurately, reduces the preferences) to move on diagonals, though it will still take diagonal moves if they are better than any orthogonal move. Using a costMap can change the preferences further, and if there is a non-default costMap in use, then equal-distance paths really become equal-preference paths, and a shorter path through mildly unpleasant territory may be chosen with equal weight against a longer path through preferred territory if the costs for each path's set of needed moves all add up to the same total.
