### ISSUE TITLE
initializeCost(double[][] cost) with only DijkstraMap.FLOOR does not seem to work

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#160]
This could be user error on my part, I'm not exactly sure how I'm supposed to be using this functionality.

**Comment by tommyettinger** [comment]
Cost maps aren't likely to be useful very often yet. They technically do apply to the cost to enter a cell, but that cell can still be chosen for a path if there is no better option. They would be more accurately called preference maps, and I thought some documentation covered them... Ah, yes, indeed I did write that. https://github.com/SquidPony/SquidLib/blob/master/squidlib-util/src/main/java/squidpony/squidai/DijkstraMap.java#L115-L123

Because DijkstraMap.FLOOR is a huge number, setting all cells to that cost makes a pathfinder averse to all cells equally, as if each cell was made of waist-deep toenail clippings, but would probably prefer to stay in one horrid cell rather than enter another equally horrid cell. If they were all set to 1.0, it would be more likely to find a path that fits in the allotted cost it can use up to get a path.
