### ISSUE TITLE
DijkstraMap uses its own measurement class instead of Radius

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#163]
This just seems weird, given that there are equivalent radius strategies in the same project. Even a converter on each of them to the other would be called for, if not an actual merging.

This is especially weird when using a FOV and DijkstraMap together with two different constants describing how they do what should be the same mathematical result (cost of angles)

**Comment by tommyettinger** [comment]
First paragraph: yes, this should be fixed, but it will break backwards compatibility if DijkstraMap changes to another enum in externally-visible variables. Conversion is fine and is already available: https://github.com/SquidPony/SquidLib/blob/master/squidlib-util/src/main/java/squidpony/squidai/DijkstraMap.java#L501-L533

Second paragraph is incorrect for the case of Euclidean measurement; FOV for more than 1 cell of radius uses a true circular shape when using `Radius.CIRCLE`, while DijkstraMap must traverse one cell at a time without knowledge of previous angles and cannot get a precise circle beyond one cell of distance. In practice, Euclidean measurement in DijkstraMap provides the same options for movement as Chebyshev, just preferring orthogonal movement when it has an equal-Chebyshev-distance choice.

Because the conversion is already available, I'll close this. It may make sense to copy the conversion into a method of the DijkstraMap.Measurement enum.
