### ISSUE TITLE
user preference saving support

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#18]
support long-term persistent storage of everything from keybindings to arbitrary perferences

**Comment by tommyettinger** [comment]
This is partially supported by squidlib-extra, at least long-term storage of various common data types. The mechanism here is libGDX's Preferences class for storing Strings, along with customized support for JSON stringification of data, plus a dependency on a lib I worked on called BlazingChain that compresses the Strings. The last one is important because on GWT targets, data saved by Preferences is limited to the size of what the browser allows for LocalStorage, and that's rather small for the one thing it can store, UTF-16-encoded text (5 MB is a common limit). Key rebinding is a significant task on its own, but it's something we should have, and something that should be store-able with squidlib-extra.

**Comment by tommyettinger** [comment]
This has been handled by Gdx `Preferences` for arbitrary things that can be saved as Strings; `squidlib-extra` wraps this somewhat in SquidStorage, but it's perfectly usable on its own without wrapping. Keybindings in particular now have their own saving system that can be shared between games that use `SquidInput` (plus a utility to remap the keys with a simple UI). In practice, the text compression (now in `squidlib-util` as `LZSPlus`) isn't very fast on GWT, but saving isn't always done especially often, and as an alternative, uncompressed saving is rather quick. Saving using libGDX's `Json` class, as SquidStorage does, relies on an odd method of reflection that can't access `long` fields, so work is in-progress to make `long` fields into pairs of `int` wherever they might need to be saved. I think this is close-able.
