### ISSUE TITLE
SquidMessageBox oddly trimming spaces during wrapping

### ISSUE THREAD

**Issue by Rakaneth** [SquidPony/SquidLib#194]
`SquidMessageBox` seems to be exhibiting some odd behavior when wrapping `IColoredString`s - it is eating spaces.

![image](https://user-images.githubusercontent.com/19420583/34647660-efbb446a-f355-11e7-820e-7ce7d16876b9.png)

This does not seem to occur in `SquidPanel` (here I used a manual `IColoredString.wrap()`):
![image](https://user-images.githubusercontent.com/19420583/34647669-4c5b04c6-f356-11e7-8af7-d4b73dc6773c.png)

The relevant code can be found [here](https://github.com/Rakaneth/wolfs-den-kotlin/blob/master/core/src/main/kotlin/wolfsden/system/CommandProcessor.kt), in the `describeCombat` function.

**Comment by tommyettinger** [comment]
Weird stuff, hm... I'll take a look as soon as I can; family is visiting Jan 7 (today in most timezones) but I should be able to take a look after they head home. I wonder what's different between the two wrapping implementations...

**Comment by tommyettinger** [comment]
This is very odd, but I've narrowed down a possible cause. Still working on a fix. It looks like (when using GDXMarkup to generate IColoredString instances) closing a color tag with `[]` before a space (but not after a space) causes wrap() to ignore the space, possibly due to the behavior of `String.split()` with delimiters at the end of input. You can see on the bottom line here, the first space gets eaten:
![](https://i.imgur.com/sB4QOsE.png)

This doesn't happen on the line above it because wrap() doesn't need to be called. The markup I'm using looks like this, where the text length is exactly within the line length for the first and one larger than the line length for the second (requiring wrapping):

```
        smb.appendWrappingMessage(GDXMarkup.instance.colorString("[CW Red]alpha[] [CW Apricot]beta [][CW Yellow]gamma [CW Jade]delta [CW Blue]epsilon [Cw Purple]zeta[]..."));
        smb.appendWrappingMessage(GDXMarkup.instance.colorString("[CW Red]alpha[] [CW Apricot]beta [][CW Yellow]gamma [CW Jade]delta [CW Blue]epsilon [Cw Purple]zeta[] eta"));
```

**Comment by tommyettinger** [comment]
This should be fixed now. The current TinyTest code that produced the above screenshot before now looks like:
![](https://i.imgur.com/sHXKFHF.png)
The issue did turn out to be `String.split()`; we now use `StringKit.split()`, which has various subtle differences including preserving trailing spaces (at the very least, it does this when they're the only contents of the String being split up).
