### ISSUE TITLE
AOE is not Serializable

### ISSUE THREAD

**Issue by Rakaneth** [SquidPony/SquidLib#196]
`AOE` is not `Serializable`, thus causing `Technique` to fail to serialize. (see #195)

**Comment by tommyettinger** [comment]
I was wondering if this chain of things would need to be made Serializable... working on it now.

**Comment by tommyettinger** [comment]
I'm only closing this tentatively because I don't know if all the AOE implementations fully work with Serializable. DijkstraMap was already Serializable; I think FOV was too (it is now). The latest commit made AOE and all its implementations Serializable, plus LOS, Spill, and SColor for good measure. I'm not sure if any of those classes use objects of some non-Serializable class, though; it's getting less and less likely that some important class is not Serializable though.
