### ISSUE TITLE
Add lighting techniques for colors similar to those used in rot.js

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#54]

**Comment by SquidPony** [comment]
With the changes to not have SColor derive from awt.Color, these back end changes can (and probably should) take place.

Personally, I very much would like to see HDR support added in.

**Comment by tommyettinger** [comment]
It seems like the HDRColor class is causing more of a headache than it helps resolve. I'm inclined to remove support for HDR (after adding it), since I can't really find good uses for it that are impossible with regular Colors. Common examples like the LerpFilter, where everything is colored with a tint, don't need HDR at all. Gamma correction is primarily useful on photos, and has limited utility on grids of text. Any things that deals with hue and saturation are exactly the same regardless of HDR, though the value/brightness component could be different. It just wreaks havoc on the OOP structure to have lots of weird additions to common things by default... I'd like @SquidPony to chime in before I take HDR out. Filters (as a thing related to SquidColorCenter) will stay, however.

**Comment by SquidPony** [comment]
I'm okay with HDRColor going away again. I'm glad however that it was successfully attempted but yeah, it spread some chaos too.

Super excited about the Filters.

**Comment by smelc** [comment]
@tommyettinger > how do you plan to do it ? Do you want to rollback the commit introducing hdr colors, continuing the current streak of changeset; or will you start again from before the introduction ?

I have a PR ready, with a few bugfixes in SquidIterators, ICombinedString (some poorly tested methods of mine) and one in DijkstraMap; but I'll wait for you, so as to be able to do the PR on the tip.

**Comment by tommyettinger** [comment]
@smelc I'm planning to refactor the code so anything that uses the HDRColor fields hr, hg, or hb instead uses r, g, or b, then I'm going to do a type migration in IntelliJ IDEA, shifting any uses of HDRColor back to libGDX Color, and I'll see if that catches everything by deleting HDRColor (I might re-add the class if we can figure out a way to compartmentalize it and not carpet-bomb the inheritance). After that, I may need your advice on where/how to use <T extends Color> since I'm not especially familiar with some of the trickier OOP concepts.

**Comment by tommyettinger** [comment]
OK, this should be done. HDRColor is deleted from the current code, anything that depended on it now can safely depend on GDX's Color, and Filters still work just fine. I'm closing this so we aren't tempted to mess with HDR and the resultant insane inheritance hierarchy any more...

**Comment by smelc** [comment]
Excellent, I'm synched again with the tip :smile:
