### ISSUE TITLE
Tile-specific background and Tile-width

### ISSUE THREAD

**Issue by MichielDeCuyper** [SquidPony/SquidLib#60]
Hello,

I just downloaded your awesome-looking library. I have two questions, concerning features I don't find the correct functionality for. I'm using v2.2:

* You promise a way to set the background-color of a tile on a tile-specific base. In v2.2, using a SquidPanel , I can't find a way to make this work. I can use setBackground(SColor color) but that's for the whole screen.

* When using a 14pt font (I followed the small example), what are the cellWidth and cellHeight I have to use to make my letters fit perfectly?

**Comment by SquidPony** [comment]
For the first point you're right that that promise is out of date. You can now actually have as many layers as you want and put a color or character in each. I'll update that with more explanation within the next day.

As for sizing exactly to a font, set the font in the builder but don't set a width or height and it will size to fit the font as fully as possible.

I see that the sizing behavior is not well documented in that regard, so I'll add updating it to my todo list.

**Comment by SquidPony** [comment]
I've updated the features list so that it more accurately reflects the current state of having multiple layers instead of being locked into only two.

I've also added some documentation regarding the sizing behavior when height and width are not passed in.

On a side note: it's impossible to manually know what size the cell will need to be to exactly fit a given font size since different systems can render them differently. Additionally antialiasing will cause them to be further rendered differently, often in unexpected ways.

For the very best fitting I recommend setting the width and height you want and then a font size equal to the largest of those two to ensure it's made to fill the cell when sized down. Furthermore I suggest having a 1 pixel padding at the top of the cell and including only the characters that you'll actually use in the "fitting" method. You can even do this for the characters you want to fit and then still used oversized characters like ▒ to give background shading without making the cells any bigger.
