### ISSUE TITLE
UnsupportedOperationException from DijkstraMap.findPathLarge

### ISSUE THREAD

**Issue by smelc** [SquidPony/SquidLib#84]
Here's a stacktrace I encounter:

~~~~~ {.java}
java.lang.UnsupportedOperationException
    at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
    at squidpony.squidai.DijkstraMap.findPathLarge(DijkstraMap.java:1610)
~~~~~~~

The problem is that I pass an unmodifiable Collection as the `impassable` parameter of `DijkstraMap.findPathLarge`. But this method can mute the collection received: see `impassable.add(currentPos)` at line 1610. I believe that `findPathLarge` should make a defensive copy (or document this dangerous behavior) if the received parameter is not-null (an additional reason is that it seems that `impassable` should be a `LinkedHashSet` (because everywhere where it is created, it is created with this type); so using the client's `Set` is wrong)(or if iteration-order doesn't matter, the sets should be `HashSet` ?).

**Comment by tommyettinger** [comment]
Good catch, I hadn't considered that this method could be passed unmodifiable Sets. I'll have it make a defensive copy of the elements in `impassable` as a LinkedHashSet.
The only reason I prefer to use LinkedHashSet and not HashSet is because Java 7, Java 8, and at least one of the two VMs used by Android iterate through HashSets in a different order (this also affects `toArray()`), so even if you used the same RNG seeds  everywhere, it would not produce the same dungeons, paths found, or other pseudo-random factors anywhere that relies on iterating through Sets. However, I don't think it ever iterates through `impassable`, or if it does, the order doesn't matter. This should be fixed in about 5 minutes.

**Comment by tommyettinger** [comment]
OK, 22 minutes. But I also fixed every other case in DijkstraMap that I could find that adds to a Set parameter... It should fix large and non-large pathfinding, for go-to paths and flee-from paths as well as the rest.
